# Generated by Django 3.0.6 on 2020-07-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200705_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModel',
            new_name='HomePageModel',
        ),
    ]
