# Generated by Django 3.0.6 on 2020-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200705_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemodel',
            name='title',
            field=models.CharField(default='DefaultTile', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepagemodel',
            name='code',
            field=models.CharField(default='DefaultCode', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagemodel',
            name='name',
            field=models.CharField(default='DefaultName', max_length=100),
        ),
    ]
