# Generated by Django 3.0.6 on 2020-07-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_create_test_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
