# Generated by Django 3.0.7 on 2020-10-10 08:28

from django.db import migrations, models
import business.product.product.models

class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_create_root_productgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=business.product.product.models.upload_to_path),
        ),
    ]
